package checkers

import (
	"context"

	"github.com/alessandrocaglio/sm3-migration-tool/pkg/discovery"
)

type routeChecker struct{}

func NewRouteChecker() Checker {
	return &routeChecker{}
}

func (c *routeChecker) Name() string {
	return "Route Checker (IOR)"
}

func (c *routeChecker) Check(ctx context.Context, state *discovery.ClusterState) ([]Finding, error) {
	var findings []Finding

	for _, smcp := range state.SM2ControlPlanes {
		spec, ok := smcp.Spec.(map[string]interface{})
		if !ok {
			continue
		}

		if gateways, ok := spec["gateways"].(map[string]interface{}); ok {
			if openshiftRoute, ok := gateways["openshiftRoute"].(map[string]interface{}); ok {
				if enabled, ok := openshiftRoute["enabled"].(bool); ok && enabled {
					findings = append(findings, Finding{
						ResourceName: smcp.Name,
						Namespace:    smcp.Namespace,
						Kind:         smcp.Kind,
						Message:      "Istio OpenShift Routing (IOR) is enabled in SMCP.",
						Severity:     SeverityHigh,
						Remediation:  RemediationGuide{
							Description: "Disable IOR by setting spec.gateways.openshiftRoute.enabled=false and migrate to explicitly managed routes or LoadBalancer services.",
							Commands:    []string{"oc patch smcp " + smcp.Name + " -n " + smcp.Namespace + " --type=json -p='[{\"op\": \"replace\", \"path\": \"/spec/gateways/openshiftRoute/enabled\", \"value\": false}]'"},
							DocsLinks:   []string{"https://docs.redhat.com/en/documentation/openshift_container_platform/4.14/html/service_mesh/migrating-from-service-mesh-2-to-service-mesh-3#service-mesh-route-migration"},
						},
					})
				}
			}
		}
	}

	for _, route := range state.Routes {
		if route.Labels != nil && route.Labels["maistra.io/generated-by"] == "ior" {
			findings = append(findings, Finding{
				ResourceName: route.Name,
				Namespace:    route.Namespace,
				Kind:         route.Kind,
				Message:      "OpenShift Route was auto-generated by IOR.",
				Severity:     SeverityHigh,
				Remediation:  RemediationGuide{
					Description: "Migrate this route to an explicitly managed Route before disabling IOR.",
					DocsLinks:   []string{"https://docs.redhat.com/en/documentation/openshift_container_platform/4.14/html/service_mesh/migrating-from-service-mesh-2-to-service-mesh-3#service-mesh-route-migration"},
				},
			})
		}
		// Also check annotations just in case
		if route.Annotations != nil && route.Annotations["maistra.io/generated-by"] == "ior" {
			findings = append(findings, Finding{
				ResourceName: route.Name,
				Namespace:    route.Namespace,
				Kind:         route.Kind,
				Message:      "OpenShift Route was auto-generated by IOR (via annotation).",
				Severity:     SeverityHigh,
				Remediation:  RemediationGuide{
					Description: "Migrate this route to an explicitly managed Route before disabling IOR.",
					DocsLinks:   []string{"https://docs.redhat.com/en/documentation/openshift_container_platform/4.14/html/service_mesh/migrating-from-service-mesh-2-to-service-mesh-3#service-mesh-route-migration"},
				},
			})
		}
	}

	return findings, nil
}
