{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sm3-migration.fullname" . }}-scanner
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["maistra.io"]
  resources: ["servicemeshcontrolplanes", "servicemeshmemberrolls"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io", "security.istio.io", "telemetry.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
{{- end -}}
